# Generated by Django 3.2.6 on 2021-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=25)),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('longitude', models.FloatField(default=0, verbose_name='Долгота')),
                ('latitude', models.FloatField(default=0, verbose_name='Широта')),
                ('temperature', models.FloatField(default=0, verbose_name='Температура')),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
    ]
